-- MySQL Script generated by MySQL Workbench
-- 02/28/16 15:14:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco_projeto_academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_projeto_academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_projeto_academia` DEFAULT CHARACTER SET utf8 ;
USE `banco_projeto_academia` ;

-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Usuarios` (
  `Login` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` CHAR(2) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `cSenha` VARCHAR(20) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `CPF` INT NOT NULL,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Treinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Treinador` (
  `CREF` INT NOT NULL,
  `Usuarios_CPF` INT NOT NULL,
  PRIMARY KEY (`CREF`),
  UNIQUE INDEX `CREF_UNIQUE` (`CREF` ASC),
  UNIQUE INDEX `Usuarios_Login_UNIQUE` (`Usuarios_CPF` ASC),
  CONSTRAINT `fk_Treinador_Usuarios`
    FOREIGN KEY (`Usuarios_CPF`)
    REFERENCES `banco_projeto_academia`.`Usuarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_CPF` INT NOT NULL,
  `Treinador_CREF` INT NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Treinador1_idx` (`Treinador_CREF` ASC),
  UNIQUE INDEX `idAluno_UNIQUE` (`idAluno` ASC),
  UNIQUE INDEX `Usuarios_CPF_UNIQUE` (`Usuarios_CPF` ASC),
  UNIQUE INDEX `Treinador_CREF_UNIQUE` (`Treinador_CREF` ASC),
  CONSTRAINT `fk_Aluno_Usuarios`
    FOREIGN KEY (`Usuarios_CPF`)
    REFERENCES `banco_projeto_academia`.`Usuarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Treinador`
    FOREIGN KEY (`Treinador_CREF`)
    REFERENCES `banco_projeto_academia`.`Treinador` (`CREF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Exercicio` (
  `idExercicio` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Musculos_Trabalhados` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExercicio`),
  UNIQUE INDEX `idExercicio_UNIQUE` (`idExercicio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Treino` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `Data_Inicio` DATE NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Objetivo` VARCHAR(45) NOT NULL,
  `Frequencia_Semanal` INT NOT NULL,
  `Numero_Treinos_Realizados` INT NOT NULL,
  PRIMARY KEY (`idTreino`),
  INDEX `fk_Treino_Aluno1_idx` (`Aluno_idAluno` ASC),
  UNIQUE INDEX `Aluno_idAluno_UNIQUE` (`Aluno_idAluno` ASC),
  UNIQUE INDEX `idTreino_UNIQUE` (`idTreino` ASC),
  CONSTRAINT `fk_Treino_Aluno`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `banco_projeto_academia`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Avaliacao_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Avaliacao_Fisica` (
  `idAvaliacao_Fisica` INT NOT NULL AUTO_INCREMENT,
  `VO2` INT NULL,
  `Frequencia_Maxima` INT NULL,
  `Zona_Alvo` INT NULL,
  `Treinador_CREF` INT NOT NULL,
  `Peso` DOUBLE NOT NULL,
  `Altura` DOUBLE NOT NULL,
  `Percentual_Gordura` DOUBLE NULL,
  `Indice_Muscular` DOUBLE NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Data` DATE NULL,
  `Horario` TIME NOT NULL,
  PRIMARY KEY (`idAvaliacao_Fisica`, `Horario`),
  INDEX `fk_Avaliação física_Treinador1_idx` (`Treinador_CREF` ASC),
  INDEX `fk_Avaliação física_Aluno1_idx` (`Aluno_idAluno` ASC),
  UNIQUE INDEX `idAvaliacao_Fisica_UNIQUE` (`idAvaliacao_Fisica` ASC),
  UNIQUE INDEX `Treinador_CREF_UNIQUE` (`Treinador_CREF` ASC),
  CONSTRAINT `fk_Avaliacao_fisica_Treinador`
    FOREIGN KEY (`Treinador_CREF`)
    REFERENCES `banco_projeto_academia`.`Treinador` (`CREF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_fisica_Aluno`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `banco_projeto_academia`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_projeto_academia`.`Treino_Exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_projeto_academia`.`Treino_Exercicio` (
  `Treino_idTreino` INT NOT NULL,
  `Exercicio_idExercicio` INT NOT NULL,
  `Data_Treino` DATE NOT NULL,
  `Quantidade_Serie` INT NOT NULL,
  `Repeticoes` INT NOT NULL,
  `Carga` DOUBLE NOT NULL,
  `Tempo_Pausa` TIME NULL,
  INDEX `fk_Treino_has_Exercicio_Exercicio1_idx` (`Exercicio_idExercicio` ASC),
  INDEX `fk_Treino_has_Exercicio_Treino1_idx` (`Treino_idTreino` ASC),
  UNIQUE INDEX `Treino_idTreino_UNIQUE` (`Treino_idTreino` ASC),
  UNIQUE INDEX `Exercicio_idExercicio_UNIQUE` (`Exercicio_idExercicio` ASC),
  CONSTRAINT `fk_Treino_has_Exercicio_Treino`
    FOREIGN KEY (`Treino_idTreino`)
    REFERENCES `banco_projeto_academia`.`Treino` (`idTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treino_has_Exercicio_Exercicio`
    FOREIGN KEY (`Exercicio_idExercicio`)
    REFERENCES `banco_projeto_academia`.`Exercicio` (`idExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


create view Nome_Aluno as select Nome from Usuarios inner join Aluno on Usuarios.CPF = Aluno.Usuarios_CPF group by Nome;
create view Nome_Treinador as select Nome from Usuarios inner join Treinador on Usuarios.CPF = Treinador.Usuarios_CPF group by Nome;